In [1]:
import pandas as pd
pd.read_parquet("infra/driver_stats.parquet")

,event_timestamp,driver_id,conv_rate,acc_rate,created,day,miles_driven,daily_miles_driven
0,2022-02-27 15:00:00+00:00,1005,0.142214,0.408987,2022-03-14 15:21:25.842,2022-02-27,24.817618,150.587752
1,2022-02-27 16:00:00+00:00,1005,0.349267,0.734021,2022-03-14 15:21:25.842,2022-02-27,8.293352,150.587752
2,2022-02-27 17:00:00+00:00,1005,0.358805,0.366804,2022-03-14 15:21:25.842,2022-02-27,8.316672,150.587752
3,2022-02-27 18:00:00+00:00,1005,0.611828,0.773883,2022-03-14 15:21:25.842,2022-02-27,10.566458,150.587752
4,2022-02-27 19:00:00+00:00,1005,0.156503,0.966413,2022-03-14 15:21:25.842,2022-02-27,15.664332,150.587752
...,...,...,...,...,...,...,...,...
1802,2022-03-14 11:00:00+00:00,1001,0.667961,0.211051,2022-03-14 15:21:25.842,2022-03-14,40.500185,350.650257
1803,2022-03-14 12:00:00+00:00,1001,0.209861,0.672022,2022-03-14 15:21:25.842,2022-03-14,21.341177,350.650257
1804,2022-03-14 13:00:00+00:00,1001,0.215754,0.791849,2022-03-14 15:21:25.842,2022-03-14,8.068214,350.650257
1805,2022-03-14 14:00:00+00:00,1001,0.404588,0.407571,2022-03-14 15:21:25.842,2022-03-14,46.533292,350.650257
1806,2021-04-12 07:00:00+00:00,1001,0.521149,0.751659,2022-03-14 15:21:25.842,2021-04-12,18.926695,18.926695